apiVersion: v1
kind: Pod
metadata:
  name: book-service
spec:
  containers:
  - name: book-service
    image: lalitagarwal91/book-service:v1
    ports:
    - containerPort: 8080
  hostName: k8s-master
