apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  selector:
    matchLabels:
      app: book-service
  replicas: 2
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: lalitagarwal91/book-service:v1
        ports:
        - containerPort: 8080
